In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.DataFrame({'text':['people watch campus' , ' campus watch campus' , 'people write comment' , 'campus write comment'], 'output':[1,1,0,0]})

In [3]:
df


text  output
0   people watch campus       1
1   campus watch campus       1
2  people write comment       0
3  campus write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv = CountVectorizer()


In [6]:
bow =cv.fit_transform(df['text'])

In [7]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campus': 0, 'write': 4, 'comment': 1}


In [8]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [9]:
cv.transform(['campus watch and write comment of campus']).toarray()

array([[2, 1, 0, 1, 1]])

n-grams

In [11]:
cv=  CountVectorizer(ngram_range=(2,2))

In [12]:
bow = cv.fit_transform(df['text'])

In [13]:
cv.vocabulary_


{'people watch': 2,
 'watch campus': 4,
 'campus watch': 0,
 'people write': 3,
 'write comment': 5,
 'campus write': 1}

In [14]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]
[[0 1 0 0 0 1]]


tf- idf

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [18]:
tfidf.idf_

array([1.22314355, 1.51082562, 1.51082562, 1.51082562, 1.51082562])

In [19]:
tfidf.get_feature_names_out()

array(['campus', 'comment', 'people', 'watch', 'write'], dtype=object)